java_library(
    name = "grpc-server",
    srcs = ["src/main/java/com/example/GrpcServer.java"],
    visibility = ["//visibility:public"],
    deps = ["@maven//:io_grpc_grpc_netty_shaded",
            "@maven//:io_grpc_grpc_api"
            ],
)
