proto_library(
    visibility = ["//visibility:public"],
    name = "hyphenation_proto",
    srcs = ["hyphenation.proto"],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "capitalization_proto",
    srcs = ["capitalization.proto"],
)